### ISSUE TITLE
Question: can I use the data.csv file?

### ISSUE THREAD

**Issue by nathakits** [taepras/thaibudget#1]
Hi, I would like to develop a website to visualize the government budget. Can I use the `data.csv` file? And also is the `data.csv`  file complete?

Best,
Nat

**Comment by taepras** [comment]
Hi,

The data.csv file was actually downloaded from KaoGeek's pdf2csv project.
While I'm happy to let you download the file, I'd recommend that you get it
from the original source which also has all the details including data
dictionaries, caution notes, etc. It can be found here:

https://docs.google.com/spreadsheets/d/1yyWXSTbq3CD_gNxks-krcSBzbszv3c_2Nq54lckoQ24/edit#gid=343539850

For your second question: yes, the file is meant to be a complete
collection of all line items listed in "เอกสารงบประมาณ (เล่มขาวคาดแดง)".
However, this is not an official file produced by the Budget Office. It was
created by the KaoGeek volunteer group by running OCR on the Budget
Office's official pdf files of the red-white books. So, some numbers may
contain some error thanks to the OCR. (But you can cross-check the items,
there are reference numbers in the dataset as described in the file I
linked above.)

Anyway, thanks for your interests and have fun exploring this dataset.
Can't wait to see what you'll come up with! 😁

Best,
Tae

**Comment by nathakits** [comment]
Thanks! Appreciate the detailed explanation 😄
